meta_product_name: "Let's Get"
meta_title: "Let's Get - Find the BEST place to meet, halfway"
meta_description: "Get help to navigate the city and find the best rated places between you and your friend."
meta_image: "favicon-meta.png"
twitter_account: "@rails"
